#!/usr/bin/env python3
"""
创建测试PDF文件用于隐写测试
"""

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import os

def create_test_pdf():
    """创建一个测试PDF文件"""
    # 创建目录
    os.makedirs("test", exist_ok=True)
    
    # 创建PDF文件
    output_path = "test/test_document.pdf"
    c = canvas.Canvas(output_path, pagesize=letter)
    
    # 添加标题
    c.setFont("Helvetica-Bold", 24)
    c.drawString(100, 750, "E2E Tool Test Document")
    
    # 添加内容
    c.setFont("Helvetica", 12)
    c.drawString(100, 700, "This is a test document for steganography testing.")
    c.drawString(100, 680, "It contains some sample text that can be used as a carrier.")
    c.drawString(100, 660, "The document will be used to test PDF steganography functionality.")
    
    # 添加更多内容
    c.drawString(100, 620, "Sample content:")
    c.drawString(100, 600, "- Line 1: Basic text content")
    c.drawString(100, 580, "- Line 2: More sample text")
    c.drawString(100, 560, "- Line 3: Additional content for testing")
    c.drawString(100, 540, "- Line 4: Final line of test content")
    
    # 添加页脚
    c.setFont("Helvetica", 10)
    c.drawString(100, 100, "Generated by E2E Tool for testing purposes")
    
    # 保存PDF
    c.save()
    print(f"✅ 测试PDF已创建: {output_path}")
    print(f"📄 PDF页数: 1")
    
    return output_path

if __name__ == "__main__":
    create_test_pdf() 